#!/usr/bin/env bash

kernel() {
  cd /opt/pve-kernel
  make all
  mv ./*.deb /opt
}

meta_packages() {
  cd /opt/pve-kernel-meta
  make deb
  mv ./*.deb /opt
}

get_sources() {
  git clone --depth 1 git://git.proxmox.com/git/pve-kernel.git /opt/pve-kernel
  git clone --depth 1 git://git.proxmox.com/git/pve-kernel-meta.git /opt/pve-kernel-meta
}
